import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Yodha",
    lastName: "Balka",
    username: "yodhabalka",
    password: "yodhaBalka123",
    email: "guest@gmail.com",
    bio: "badminton | Web Developer",
    website: "https//google.com",
    img: "https://i.imgur.com/2MVjicu.png",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
  _id: uuid(),
  firstName: "John",
  lastName: "Quil",
  username: "JohnQuil55",
  password: "john23",
  email : "john@gmail.com",
  bio: "Hy, i am aspiring web developer",
  website : "https//john.com",
  img : "https://imgur.com/nkLKUOF.jpg",
  createdAt: formatDate(),
  updatedAt: formatDate(),
},
{
  _id: uuid(),
  firstName: "Cherry",
  lastName: "Blossom",
  username: "Cherry34",
  password: "cherry123",
  email : "cherry@gmail.com",
  bio: "Hy, i am aspiring Vue js developer",
  website : "https//Cherry.com",
  img : "https://imgur.com/HI0YwQK.png",
  createdAt: formatDate(),
  updatedAt: formatDate(),
},
{
  _id: uuid(),
  firstName: "Liza",
  lastName: "Doolittle",
  username: "Liza444",
  password: "liza123",
  email : "liza@gmail.com",
  bio: "Hy, i am aspiring React native developer",
  website : "https//liza.com",
  createdAt: formatDate(),
  img : "https://imgur.com/yDukBth.png",
  updatedAt: formatDate(),
},
{
  _id: uuid(),
  firstName: "Chris",
  lastName: "Bacon",
  username: "ChrisVolter",
  password: "chris123",
  email : "chris@gmail.com",
  bio: "Hy, i am aspiring Angular developer",
  website : "https//chris.com",
  img : "https://imgur.com/uDOAYQ9.png",
  createdAt: formatDate(),
  updatedAt: formatDate(),
},
{
  _id: uuid(),
  firstName: "Jack",
  lastName: "Aranda",
  username: "jack007",
  password: "jack123",
  email : "jack@gmail.com",
  bio: "Hy, i am aspiring React developer",
  website : "https//jack.com",
  img : "https://i.imgur.com/oHTOZNL.png",
  createdAt: formatDate(),
  updatedAt: formatDate(),
},
];
